### ISSUE TITLE
offset signal

### ISSUE THREAD

**Issue by forceformatnik** [TylerAdkisson/SignalTest#1]
Hi, I would like to ask a few questions about demodulation of offset signals.

**Comment by TylerAdkisson** [comment]
If it would be alright with you, I would prefer if you could ask your questions here in this issue.  That way, in the future, others could possibly learn as well.

**Comment by forceformatnik** [comment]
Thank you for your answer, on this scheme, oqpsk signal modulator, demonstrated a delay with a period of T / 2, it's understandable, well, where should there be a delay in demodulation, for example the oqpsk signal. If I'm not right, do I need to delay at all when demodulating this signal. If you can then demonstrate an example in the code for modulation and demodulation of signals of offset type.
![picture_picblock_a_4](https://user-images.githubusercontent.com/37415449/37826125-f25b9e6a-2e9a-11e8-87f6-0d57316b6972.gif)

**Comment by forceformatnik** [comment]
Another question is the difference in the demodulation of narrowband and broadband signals. I think the main difference is in PLL implementation.

**Comment by TylerAdkisson** [comment]
**On the subject of offset QPSK,**

In the modulator, as you already know, there is a delay of half of a symbol period (T / 2) on the Q line.  This offsets the I and Q signals so they will never both change phase at the same time.  This is done to reduce the amplitude variation in the output signal which results in the signal being less susceptible to non-linear effects during transmission.  This is important as it allows the use of non-linear amplifiers which are more power efficient than linear amplifiers.

Here is a block diagram of an OQPSK modulator:
![oqpsk modulator](https://user-images.githubusercontent.com/413727/37946349-e857593a-3152-11e8-84c3-895e00bc5fdd.png)

Since there was a delay during modulation, there must also be an equal delay (T / 2) during demodulation to ensure the bits sync back up.  This delay is added on the I side instead because the delay was added on the Q side during modulation.

And here is a block diagram of an OQPSK demodulator:
![oqpsk demodulator](https://user-images.githubusercontent.com/413727/37946803-62199178-3155-11e8-8097-d7a8a4e63225.png)

The demodulator is comprised of a QPSK costas loop (on the left before the first set of decimators) followed by a symbol timing detector and symbol slicer.  The output is a series of soft symbols.  This diagram is leaving out some pieces of a complete demodulator, such as a matched filter (for pulse shaping), symbol decision, and bit interleaver, among other things.

**Note:** One important piece missing from this demodulator is a unique word/preamble detector to resolve the inherent 90 degree phase ambiguity that exists in the output of this kind of demodulator.  Without resolving the phase ambiguity, the I and Q channels may be swapped and/or inverted (this happens when the 4 point constellation is rotated away from its proper orientation).

I have implemented both the modulator and demodulator shown above in Examples/QPSK.cs


**As for narrowband vs broadband signals,**

From what I understand, the primary deciding factor is filter bandwidth.  In a PLL (and thus a costas loop), the loop filter bandwidth determines how far away the loop can 'pull in' a signal for carrier tracking and syncing phase with the signal.  If the loop bandwidth is too narrow, the loop will not be able to track the desired signal.  If the the loop bandwidth is too wide, the loop is more susceptible to noise.
While writing the examples, I tested the code against both a 250 symbols/s (500 bps) signal and against a 5250 symbol/s (10500 bps) signal with the only changes being the loop bandwidth (`costas.ArmFilterHz` in the example code, based on symbol rate) and input sample rate.

**Comment by forceformatnik** [comment]
Thanks for your full answer. I would like to clarify one more interesting thing about the process of decimation. It is known that as the decimation factor increases, signal reception deteriorates. By the Kotelnikov theorem, the relation must be 1/2. Where is the decimation process implemented in your code?

**Comment by forceformatnik** [comment]
Sorry, did not look in the code, immediately asked a question. Everything is clear now, thank you very much for your help.

**Comment by TylerAdkisson** [comment]
You're welcome, I'm glad to help.

Even though you already figured it out, I will clarify the decimation used in the demodulator in case someone else comes across this in the future.

The first 2x symbol rate/baud decimation is implemented with fractional rate downsamplers in the example code by `dsI` and `dsQ`.  These take the input signal at its full sampling rate (8000 samples/s in the example) and reduce it down to 2 samples per symbol (which is 2x the symbol rate) as required for the modified gardner timing error detector to function.

The final decimation further reduces the sampling rate down to the 1 sample per symbol (which is equal to the symbol rate).  This decimation is very simple and is implemented with a toggle flip-flop to output every other sample.

**Comment by forceformatnik** [comment]
Thank you for your answer, this is very useful information. I would like to ask about the process of demodulation of qam signals. What are the peculiarities in the implementation of demodulators of this type? I will be very grateful if you answer this question.

**Comment by TylerAdkisson** [comment]
Quadrature Amplitude Modulation (QAM for short) combines Phase Shift Keying (PSK) and Amplitude Modulation (AM) to store more many bits per symbol than normal PSK.  A digital QAM signal is similar in structure to a regular QPSK signal, except the I and Q channels are multi-level signals instead of bi-level signals.  This can be seen in the images below.

First a QPSK signal:
![QPSK symbols with constellation diagram](https://user-images.githubusercontent.com/413727/38167621-2d61089e-3506-11e8-8da4-471e94369943.png)

Each signal in the I and Q channels can be of two levels, resulting in 2 x 2 = 4 possible symbol values.

Now for QAM-16:
![QAM 16 symbols with constellation diagram](https://user-images.githubusercontent.com/413727/38167628-3a29c57a-3506-11e8-98b4-5a46994ef736.png)

As shown in the diagram above, the QAM-16's I and Q signals each can be one of 4 different levels, resulting in 4 x 4 = 16 different symbols, as shown in the constellation diagram on the right.
Initially, you might think since the signals seem so similar that you could use a QPSK demodulator with a QAM signal.  This does not work for a few reasons:

One reason is the QPSK phase error detector is only expecting phase changes in multiples of 90 degrees, where a QAM signal's phase changes have a smaller-angle granularity than 90 degrees.  The actual value depends on what level of QAM used.  QAM's use of AM also causes issues with QPSK's phase error detection.

Another thing the AM component of QAM changes is how the timing recovery has to be done.  A normal Gardner timing detector only works with bi-level signals, as it requires a zero-crossing to be able to detect proper timing.  The I and Q channels of a QAM signal may stay on one side of zero for several symbol periods, preventing Garnder from calculating a proper timing error value.

Because of these issues, QAM demodulators can use what's called decision-directed carrier recovery along-side another type of timing error detection (I personally have used a modified Gardner timing error detector that only computes timing error if it detects a zero crossing.  Available as Gardner.cs).  In a somewhat simple view, decision-directed carrier recovery determines which constellation point the received symbol is closest to, then computes the phase angle difference between the two.  This phase difference is then used as the phase error in the carrier recovery loop to tune the VCO.
When coupled with a set of initial training symbols (also called a unique word or preamble) during modulation, this method can correct both the carrier phase/frequency error and the constellation rotation.

**Comment by forceformatnik** [comment]
Thanks for your full answer, thanks for the help. It would be very interesting to hear more about some interesting things about demodulation of signals, if you want to tell something else, I'll be glad to learn something new

**Comment by forceformatnik** [comment]
Hello, I want to ask how to determine the level of signal / noise (SNR)?

**Comment by TylerAdkisson** [comment]
Sorry for the delay.

Estimation of SNR is something I've had difficulty with, as there doesn't seem to be one "standard" way of doing it.
I've only ever worked it out on paper, but one of the ways I have come across that seems to make sense for PSK and QAM signals is error vector magnitude.  Error vector magnitude, or EVM, is a measurement of the distance (in I/Q space) between a received symbol and its proper constellation position.

![Error vector magnitude of a QPSK signal diagram](https://user-images.githubusercontent.com/413727/38758977-99109092-3f41-11e8-80a3-2baba7fdad69.png)

This gives you noise amplitude relative to signal amplitude.  This value can be converted to SNR via a simple equation:
```
SNR = -(20 * log10(error_vector_magnitude / constellation_point_magnitude) )
```
This will give you the SNR value for each received symbol, which can then be averaged out over several symbols to arrive at an average SNR value.

One thing to note about EVM is it works best when you have a known set of training symbols (typically in a preamble) to compute the EVM with.  Without a set of known symbols, the computed EVM (and thus SNR) values will become less accurate as the real SNR decreases.

**Comment by forceformatnik** [comment]
Thank you for your answer, I would like to ask for the reception of blasting signals. Do I think that these signals need to be taken on a level?

**Comment by TylerAdkisson** [comment]
I don't believe I understand what you mean by "blasting" signals, nor what "taken on a level" means in this context.

**Comment by forceformatnik** [comment]
Sorry for the incorrect translation, I wanted to ask about burst signals.

**Comment by TylerAdkisson** [comment]
It's alright.  What did you want to know about burst signals?

Data-carrying digital burst signals are commonly short in length, composed of a short set of training symbols (also known as a preamble) at the start, followed by a somewhat short sequence of data symbols.  The preamble is crafted to allow the receiver to quickly acquire carrier and symbol timing lock before the beginning of the data symbols.  Burst signals are commonly used in packet-based wireless systems, like Wi-Fi, and some satellite communication systems.

This is in contrast to non-burst signals which may start with a long set of training symbols, or possibly pilot tones and can potentially have no upper limit on length of data symbols.  These signals can have better detection characteristics in the presence of noise, as there is more time to acquire carrier and symbol timing lock.

**Comment by zhaohengbo** [comment]
Could you please give a brief description of what the code of channelequalizer is used for?
By the way,could you recommend some books in reference to these theory?

**Comment by TylerAdkisson** [comment]
Sorry for the _very_ late response.
It has been a long time since I wrote this code, so some of the details may not be very clear to me.


The `ChannelEqualizer` class implements the Normalized Least Mean Squares (N-LMS) adaptive complex equalizer.  This equalizer uses complex (I/Q) samples in the form of `float` pairs.

The class mostly takes the form of a standard Finite Impulse Response (FIR) filter, with the following functions:

* `AddData()` - Shifts a complex sample into the buffer
* `Process()` - Runs the FIR filter over the buffered data
* `Update()` - Adjusts the LMS filter coefficients

While the functions `AddData()` and `Process()` are pretty uninteresting, the `Update()` function is where the magic happens:
The function takes in a complex sample as the `decisionSampleI` and `decisionSampleQ` parameters.

```cs
// Update filter coefficients
float errorI = decisionSampleI - _lastResultI;
float errorQ = decisionSampleQ - _lastResultQ;
```
This calculates the difference (error) between the last filter output and the desired filter output.

```cs
float normalization = 1.1755e-38f;

// Normalize based on the power of the input samples
// This prevents the amplitude of the input from adversely affecting the stability
//   of the filter update
for (int i = 0; i < _coeffBufferI.Length; i++)
	normalization += (_firBufferI[i] * _firBufferI[i]) + (_firBufferQ[i] * _firBufferQ[i]);
```
This calculates the power of the past input samples to allow us to adjust the effective learning rate based on input signal amplitude.

```cs
for (int i = 0; i < _coeffBufferI.Length; i++)
{
	float tempI, tempQ;
	// _firBufferQ is inverted to swap the multiply operation's signs from +, - to -, +
	ComplexMultiply(_firBufferI[i], -_firBufferQ[i], errorI, errorQ, out tempI, out tempQ);
	tempI *= AdaptRate;
	tempQ *= AdaptRate;

	tempI /= normalization;
	tempQ /= normalization;

	_coeffBufferI[i] += tempI;
	_coeffBufferQ[i] += tempQ;
}
```
This is the meat of the algorithm.  It multiplies each complex input sample with the error value computed
earlier, then multiplies the result by the adaption rate, and divided by the normalization value.  This
value is then added to the coefficients, adapting the filter tap values.

As for reference material or books for this and related topics, I do not have and recommendations, as I
originally built this after reading a bunch of different materials about this subject, eventually being
able to build something that worked.  I remember reading a bunch of papers and slides about adaptive
filtering, but it turns out I unfortunately didn't bookmark the material that really helped me along.

**Comment by zhaohengbo** [comment]
Thanks a lot !
